NOISSUE - Add TLS Certs Loading and Certificate Revocation
absmach/mproxy pull request #57
Opened 2024-02-28 11:25 UTC by arvindh123

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Add TLS Certs Loading and Certificate Revocation 

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2024-03-07 12:12 UTC, dborovcanin requested changes

2024-03-07 12:12 UTC, dborovcanin commented on .gitignore
> +ssl/certs/*
Add the empty line.

2024-03-07 12:12 UTC, dborovcanin commented on examples/client/http/with_mtls.sh
> +curl -sSiX POST "${protocol}://${host}:${port}/${path}" -H "content-type:${content}" -H "Authorization:TOKEN" -d "${message}" 2>&1
Same here.

2024-03-07 12:12 UTC, dborovcanin commented on examples/client/http/without_tls.sh
> +curl -sSiX POST "${protocol}://${host}:${port}/${invalidPath}" -H "content-type:${content}" -H "Authorization:TOKEN" -d "${message}"
And here.

2024-03-07 12:20 UTC, arvindh123 commented on .gitignore
> +ssl/certs/*
done

2024-03-07 12:20 UTC, arvindh123 commented on examples/client/http/without_tls.sh
> +curl -sSiX POST "${protocol}://${host}:${port}/${invalidPath}" -H "content-type:${content}" -H "Authorization:TOKEN" -d "${message}"
done

2024-03-11 11:12 UTC, dborovcanin requested changes
Please update Readme with details on how to use examples and create relevant certificates using Makefile.

2024-03-11 15:59 UTC, dborovcanin requested changes

2024-03-11 15:59 UTC, dborovcanin commented on config.go
> +	if len(opts.FuncMap) == 0 {
Use switch instead of `if-else`.

2024-03-11 15:59 UTC, dborovcanin commented on pkg/tls/tls.go
> +	CRLDistributionPointsIssuerCertFile string           `env:"CRL_DISTRIBUTION_POINTS_ISSUER_CERT_FILE "  envDefault:""`
Extract these (revocation config) to a separate struct in a separate file.

2024-03-11 15:59 UTC, dborovcanin commented on pkg/tls/tls.go
> +func (c *Config) Load() (*tls.Config, Security, error) {
Let's not return `Security` here. Returning `nil, nil` to indicate no config and no error seems a little cryptic (while correct, so I would suggest using the `ErrNoTLS` error to indicate no error, but also no TLS; so you can later have something like:
```
	l, err := net.Listen("tcp", p.config.Address)
	if err != nil {
		return err
	}
	tlsCfg, err := p.config.TLSConfig.Load()
	switch err {
	case nil:
		l = tls.NewListener(l, tlsCfg)
	case mptls.ErrNoTLS:
		break
	default:
		return err
	}
```
While this means we first start the listener and then parse the TLS config, this order is not so important; we can't have one without the other anyways.

2024-03-11 15:59 UTC, dborovcanin commented on pkg/tls/tls.go
> +func (c *Config) verifyPeerCertificate(rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error {
Move this alongside the new file for revocation config.

2024-03-11 15:59 UTC, dborovcanin commented on pkg/tls/tls.go
> +				return fmt.Errorf("neither the issuer certificate is present in the chain nor is the issuer certificate URL present in AIA, certificate common name %s  and serial number %x", peerCertificate.Subj
Extract large strings to constants. Try to simplify the method.

2024-03-11 15:59 UTC, dborovcanin commented on pkg/tls/tls.go
> +func (c *Config) verifyPeerCertificate(rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error {
Also, this method looks very complex. Can you try to simplify or, at least, split?

2024-03-15 13:52 UTC, dborovcanin requested changes
Replace `if-else` with `switch`.

2024-03-15 13:52 UTC, dborovcanin commented on pkg/tls/tls.go
> +}
Let's remove this whole construct and replace it with:
```go
func Status(c Config) string {
	if c.CertFile == "" && c.KeyFile == "" {
		return "TLS"
	}

	if c.ClientCAFile != "" {
		if len(c.ClientValidation.ValidationMethods) > 0 {
			return "mTLS with client verification"
		}
		return "mTLS"
	}

	return "no TLS"
}
```
In `main.go` we have:
```go
p.logger.Info(fmt.Sprintf("HTTP proxy server at %s%s with %s exiting with errors", p.config.Address, p.config.PrefixPath, mptls.Status(p.config.TLSConfig)), slog.String("error", err.Error()))
```

2024-03-15 13:52 UTC, dborovcanin commented on pkg/tls/validations.go
> +// Copyright (c) Abstract Machines
Rename to `verifier`. Also, separate OCSP and CRL into subpackages.

2024-03-21 11:42 UTC, dborovcanin requested changes

2024-03-21 11:42 UTC, dborovcanin commented on pkg/tls/tls.go
> +func (c *Config) Security() Security {
Use this as a util function, do not use Config receiver. Also, move it to a different package.

2024-03-21 11:42 UTC, dborovcanin commented on pkg/tls/tls.go
> +func (c *Config) SecurityStatus() string {
Same here, remove; use util method.

2024-03-21 11:42 UTC, dborovcanin commented on pkg/tls/tls.go
> +func (s Security) String() string {
Remove, we do not need a new type; use the util method to determine log levels.

2024-03-21 11:42 UTC, dborovcanin commented on pkg/tls/tls.go
> +	Verifier     verifier.Config
Replace with the list of verifiers, where Verifier is:
```go
type Verifier interface {
	// VerifyPeerCertificate...
	VerifyPeerCertificate(rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error
}
```
and in the Config we have:

```go
func (c *Config) VerifyPeerCertificate(rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error {
	for _, v := range c.Verifiers {
		if err := v.VerifyPeerCertificate(rawCerts, verifiedChains); err != nil {
			return err
		}
	}
	return nil
}
```
And you use different implementations of Verifier `ocsp` and `crl` just like you already did.

2024-03-21 11:42 UTC, dborovcanin commented on pkg/tls/tls.go
> +			tlsConfig.VerifyPeerCertificate = c.Verifier.VerifyPeerCertificate
And here it would be something like:
```go
		tlsConfig.VerifyPeerCertificate = c.VerifyPeerCertificate
```

2024-03-27 15:36 UTC, dborovcanin requested changes
Please fix CI liner comments.

2024-04-03 11:59 UTC, dborovcanin approved these changes

2024-04-04 14:16 UTC, dborovcanin requested changes

2024-04-04 14:51 UTC, dborovcanin requested changes

2024-04-04 14:51 UTC, dborovcanin commented on examples/server/mosquitto/server.conf
> +protocol websockets
Please add `allow_anonymous true` to allow using more recent Mosquitto versions.

2024-04-04 14:59 UTC, dborovcanin approved these changes

2024-04-04 14:59 UTC, merged